"""backref relationships between User, Expense and ExpenseShare

Revision ID: f5e59d721dea
Revises: 2ba3946ed820
Create Date: 2020-02-11 14:47:17.537761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e59d721dea'
down_revision = '2ba3946ed820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense_share', 'share',
               existing_type=sa.REAL(),
               nullable=False)
    op.drop_column('expense_share', 'credit')
    op.drop_column('expense_share', 'debit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_share', sa.Column('debit', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('expense_share', sa.Column('credit', sa.REAL(), autoincrement=False, nullable=False))
    op.alter_column('expense_share', 'share',
               existing_type=sa.REAL(),
               nullable=True)
    # ### end Alembic commands ###
