"""Add expense_id foreign key to ExpenseShare

Revision ID: fdce608c039a
Revises: f5e59d721dea
Create Date: 2020-02-11 15:15:23.836108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdce608c039a'
down_revision = 'f5e59d721dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'expense_share', 'expense', ['expense_id'], ['expense_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_share', type_='foreignkey')
    # ### end Alembic commands ###
